apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy09
  labels:
    app: autodeploy09
  namespace: namespace-workflow-1696330096689
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy09
  template:
    metadata:
      labels:
        app: autodeploy09
    spec:
      containers:
        - name: autodeploy09
          image: acrworkflow1696330096689.azurecr.io/image-workflow-1696330096689:latest
          ports:
            - containerPort: 5000